# Generated by Django 2.2.1 on 2019-05-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseClassify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='predict_image',
            field=models.FileField(upload_to='predict_image/'),
        ),
    ]
