# Generated by Django 2.2.1 on 2019-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseaseClassify', '0002_auto_20190515_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='predict_image',
            field=models.FileField(blank=True, null=True, upload_to='predict_image/'),
        ),
    ]
